# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a0e9ccab5ef498bf0633d5a784f038e85657bf57b356913320bfc2bad8ba397115320667aa8b2c9187aef3ae8714e7a8a21bce9ada6f45bae0f8f24135dbb9c

test:
  secret_key_base: 97c387a915f8cf5f5653f07145a0492d1d59bc6a7dac9d843243fe3a1502caf02c097879d76754b3bfbe4b16f25b6cddf87ce044d8b9e2bc6daaacb0a1aaf5f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
